### ISSUE TITLE
Recaptcha Issue

### ISSUE THREAD

**Issue by AdamDanischewski** [Michael-J-Scofield/plebbit#1]
Hi, I just started learning Laravel and played around with this code it looks promising. I didn't see any mention in the instructions that you need a recaptcha API key, I set it up yet it doesn't work so far. I have modified the  recaptcha.php file yet that is not found automatically in captchav2.blade.php - I hardcoded it for now in captchav2.blade.php the Captcha box now shows up (at registering a new user) yet it fails to authenticate each time. Any ideas what may be the problem?  

The error message is: `The g-recaptcha-response field is required.`

**Comment by AdamDanischewski** [comment]
Is there a quick/easy way to disable recaptcha?

**Comment by AdamDanischewski** [comment]
I missed the configuration in .env for recaptcha (I think when I grep'd the plebbit dir I must have used case sensitive). New to Laravel, it's working well now.

**Comment by Michael-J-Scofield** [comment]
Glad you solved it! I should probably write a more detailed installation guide.
