### ISSUE TITLE
Request :)

### ISSUE THREAD

**Issue by husleuujii** [Michael-J-Scofield/plebbit#12]
1- Im having an idea that on front page (home page).
Can you show trending or new subplebbit and showing most popular users (Who is more active, submitting or getting karma point). 
[https://imgur.com/a/x067KNx](url) Like that, 
2- When submitting GIF type image, the GIF doesnt working correctly, I think GIF shoud play right? 
Please , Sir

**Comment by husleuujii** [comment]
Hello are u there? What is ur Email? I have a offer to you :)

**Comment by Michael-J-Scofield** [comment]
hey man, sorry for the few months late reply. my email is michaelscofield4554@gmail.com

**Comment by husleuujii** [comment]
its fine hehe, Please,can u do trending or new subplebbit? on the frontpage,

**Comment by Michael-J-Scofield** [comment]
currently don't have time to work on this project.

**Comment by husleuujii** [comment]
alright, anyway i have some redesign , if u mind u can merge

**Comment by Michael-J-Scofield** [comment]
cool, if you submit a pull request Ill take a look at it.
