### ISSUE TITLE
[Suggestions]

### ISSUE THREAD

**Issue by AdamDanischewski** [Michael-J-Scofield/plebbit#2]
Now that I've got it to work somewhat, I have noticed a few things: 

When making a new post, existing Subplebbit's are not displayed, they should probably be enumerated and added to a drop down. 

It would be nice to add the style feature selection to the creation of the Subplebbit. 

When you subscribe to a Subplebbit it does not immediately update the my subplebbit's drop down on the top of the screen (probably needs to be attached to an event trigger). 

I created a fork, I don't have much time to work on this - I used to know PHP well, yet have been utilizing other languages for the last several years. If I add anything interesting (maybe some HTML5, I'll let you know). I plan to update the documentation to provide instructions that work from a bare bones install of Laravel so it "works out of the box" - and maybe provide a script.

**Comment by Michael-J-Scofield** [comment]
Hi Adam, 

Thanks for checking out my project. When you start typing in the subplebbits field when creating a new post it should suggest you existing ones. (this can be improved a lot though)

I 100% agree with item3 and Ill probably implement that next week along with a push for some missing directories which might make the installation a bit harder.

And thanks for forking! Feel free to mess around and open a pull request when you've made anything. I can always look at your code and give tips/improve it 👍 

edit: just made a push for adding some folders and updating the sub plebbit instantly upon subscribing. Thanks again for the suggestions 😄

**Comment by AdamDanischewski** [comment]
Hi Michael, glad to hear from you - if I make any changes or add documentation/scripts I will pass it on. I'd like to make a script/doc for people to get started playing around with this to have a reliable guaranteed workflow to getting it going. Since I figured it out (some undocumented things that I needed) and didn't keep track I'll have to get a virtual instance going to test. I have been dealing with trying to get this deployed on a shared host and it's been challenging - its almost up, composer is installed yet it's an apache deploy, I haven't tested it locally this way yet. 

I'm hoping to eventually shape this software into what [http://voat.co](http://voat.co) has done (it's also a reddit clone) except in PHP (not .NET).

**Comment by Michael-J-Scofield** [comment]
Please do, any contributions are more then welcome 😄 Also let me know when you've deployed it. I personally don't recommend deploying Laravel on a shared host if you can't change the webroot. But I hope it works out for you! 

And what voat.co has build is exactly my goal, and keep in mind plebbit is in Php too 😉

**Comment by husleuujii** [comment]
how to do? how to confige.. help me
