### ISSUE TITLE
Alert notif got some error

### ISSUE THREAD

**Issue by husleuujii** [Michael-J-Scofield/plebbit#4]
On my localhost, Comment reply was working fine. After i uploaded to my server. Notification of reply is not working it directly shows up home page?. But message notif working fine on server.

**Comment by Michael-J-Scofield** [comment]
Please give more detailed information about your server environment.

**Comment by husleuujii** [comment]
[https://imgur.com/SXCXsnX](url)  HI, sir.  I mean notification is not working. When i click on notification it does not showing anything just going to home. But in localhost i m able to check my reply  [https://imgur.com/ZDpdxmm](url). I got 1 more error if someone comment on my post, its not going to alert. Only reply is alerting

**Comment by husleuujii** [comment]
[img]https://i.imgur.com/ZDpdxmm.jpg[/img]

**Comment by husleuujii** [comment]
https://imgur.com/a/dmmnIa7 , first link

**Comment by Michael-J-Scofield** [comment]
I don't know about the local vs server issue but I will make it send an alert when someone comments on your post.

**Comment by husleuujii** [comment]
love you man, you r so good coder. Im learning a lot of things from your Plebbit. :)

**Comment by Michael-J-Scofield** [comment]
Thanks glad you're learning 👍 pushed for alerts, see: https://github.com/Michael-J-Scofield/plebbit/commit/4417e83f637938d0f89569f07651eb30441bbbcb
