### ISSUE TITLE
Submitting a post throws an error

### ISSUE THREAD

**Issue by xooxgit** [Michael-J-Scofield/plebbit#5]
Not able to submit a new post. Reads, "Whoops. Something went wrong"

**Comment by Michael-J-Scofield** [comment]
on the live site? if not what was the error message

edit: I forgot to install curl when updating php. fixed now.

**Comment by xooxgit** [comment]
Yes, I created a new subreddit and posted a Youtube link there. This is the page I am taken to. 
![git](https://user-images.githubusercontent.com/39488927/40833414-7d636a1e-65ab-11e8-9ea2-3b3c14c2f126.png)

**Comment by Michael-J-Scofield** [comment]
fixed. please try now.

**Comment by xooxgit** [comment]
Thank you very much. I am considering using plebbit source code for my site. Was this an issue that could cause trouble?

**Comment by Michael-J-Scofield** [comment]
It was a server configuration issue ;)

please let me know if you need help.
