### ISSUE TITLE
Php artisan migrate not working

### ISSUE THREAD

**Issue by xooxgit** [Michael-J-Scofield/plebbit#6]
Hi, 

I just created the .env file and the final step was to use the php artisan migrate command. But I get this error. Any idea how I can fix this? Thanks a lot. 
![git](https://user-images.githubusercontent.com/39488927/40838832-72046012-65bd-11e8-8f09-1f10a5c31b4d.png)

**Comment by Michael-J-Scofield** [comment]
what's in the plebbit directory? it looks like it couldn't import the `vendor/autoload.php` which could be a permission issue as well.

**Comment by xooxgit** [comment]
The file does exist and here are the folder and file permissions:

bootstrap folder: drwxr-xr-x
autoload.php: -rw--r--r--

I am accessing this as root. So this does mean I should be able to read and write. Also, this is the autoload.php page. Everything is what's default. Not really sure what the issue is. 

Thank you for all your help. 
![git](https://user-images.githubusercontent.com/39488927/40870088-53f9474e-6645-11e8-95f3-73f46b3d6eae.png)

**Comment by Michael-J-Scofield** [comment]
Do you have the vendor folder?

**Comment by xooxgit** [comment]
No, I do not. I have checked both bootstrap as well as the plebbit folder. I don't find it on either. Where should it exist? Thanks for all the help here!

**Comment by Michael-J-Scofield** [comment]
Run ```composer install``` as documented in the installation guide.  If you don't have composer, install it.

**Comment by xooxgit** [comment]
No luck. I had already done composer install and created a .env file. Still the same issue. I ran composer install again and I still don't see a vendor folder on the bootstrap folder.

**Comment by Michael-J-Scofield** [comment]
vendor folder should be in the root of the project not in the bootstrap folder.

fix your composer. this is not related to the project but to your config.

please see: https://medium.com/@colorfield/install-an-existing-laravel-project-c6e6bf28d5c6
and: https://getcomposer.org/download/
