### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by husleuujii** [Michael-J-Scofield/plebbit#8]
I faced big problem, last issue I told you about local server`s Notification working but doesnt working on real website. When I created subplebbit as user(not as admin id), Im not able to edit. But on my localhost its working fine. So my host is Cpanel. Do u have any suggestion? I really want to work it. Cant really fix this issue. 1 more thing is new user registered how do u showing  https://plebbit.net/p/announcements/comments/rules/welcome-to-plebbit this subplebbit.

https://imgur.com/a/Eb42ytV  (Screenshot from website)
https://imgur.com/a/0xPn05b (Screenshot from website) ,
And did u checked your AMP? showing regular mobile view.

**Comment by Michael-J-Scofield** [comment]
Thanks for reporting your issue. Ill try to break your questions up in separate sections to answer them more efficiently.

**Hosting issues**
Are you using cpanel with shared hosting? How did you set the project up on the host?
I haven't been able to reproduce the permission issue nor the notification issues so I hope you can write down your steps in more detail. For the permission issue it might be good to know that moderators can't edit the subplebbits. Only the creator and admin can do that.

Also can you please check that no private files are exposed on your host. For example: `yourdomain.com/.env` should not be visible to the public.

**Redirect after activation**
For the redirect after registration you can fill in the `REDIRECT_CREATE_ACC` entry in your `.env` file or if you have email activation enabled: `REDIRECT_ACTIVATION`

**Google amp**
Google amp seems to be working for me. You can check the amp pages for development by adding `/amp` after the domain so [plebbit.net/amp/p/announcements/comments/rules/welcome-to-plebbit](https://plebbit.net/amp/p/announcements/comments/rules/welcome-to-plebbit) for example.

To check if the amp page is valid you can add `#development=1` to the url.
example: [plebbit.net/amp/p/announcements/comments/rules/welcome-to-plebbit#development=1](https://plebbit.net/amp/p/announcements/comments/rules/welcome-to-plebbit#development=1)
*check the console for errors*

To validate and see a search result preview you can use the [online validator from google](https://search.google.com/test/amp)

**Comment by husleuujii** [comment]
Yes,I m using shared hosting. I separated my laravel into 2 file, like this:

require __DIR__.’/../myLaravelProject/bootstrap/autoload.php’;
 
$app = require_once __DIR__.’/../myLaravelProject/bootstrap/app.php’;
then laravel worket didnt set other things.

**Comment by Michael-J-Scofield** [comment]
I take it your private and public folders are different. Have you been able to run the latest db migrations?

**Comment by husleuujii** [comment]
yes, i did it by manually. I created db on phpMyadmin hehe. before db migration it wasnt also working. it could be server issue,
how about this php extensions? https://imgur.com/a/f7LhS7I

**Comment by husleuujii** [comment]
live clone of Plebbit , m.meepo.mn, so mine is meepo.mn . Can you check? register and try check notif either create Subplebbit n try edit. hehe

**Comment by Michael-J-Scofield** [comment]
Can't register as your recaptcha isn't working. I would recommend to host on a vps instead of shared hosting where you can't run migrations etc.

**Comment by husleuujii** [comment]
okay, thanks you sir.

**Comment by TeamChang** [comment]
hello Michael-J-Scofield, how can one setup registration/login with google and facebook? and if you have done it please share. thankyou in advance. awaiting your reply

**Comment by Michael-J-Scofield** [comment]
You can use [Laravel Socialite](https://laravel.com/docs/5.6/socialite)

**Comment by TeamChang** [comment]
okay thank you
